MetaTrader5:
  Login: 145688
  Password: "X9vyB7%90i"
  Server: FusionMarkets-Demo
  Timeout: 60000
FetchingSettings:
  DefaultPair: "XAUUSD"
  SplittingRatio:
    Training: 70
    Validation: 15
    Testing: 15
  DefaultTimeperiod: 2001
  DefaultTimeframe: "H1"
Database:
  Host: "localhost"
  Port: 1433
  User: "app_user"
  Password: "password01!"
  Database: "TestDB"
GoldTradingSettings:
  Indicators:
    MovingAverages:
      SMA:
        Periods: [5, 8, 13, 21, 50, 200]
      EMA:
        Periods: [5, 8, 13, 21, 50, 200]
      MACD:
        FastPeriod: 12
        SlowPeriod: 26
        SignalPeriod: 9
    Volatility:
      BollingerBands:
        Period: 20
        NumStd: 2.0
      ATR:
        Period: 14
    Momentum:
      RSI:
        Period: 14
        OverBought: 70
        OverSold: 30
      Stochastic:
        KPeriod: 14
        DPeriod: 3
        SlowingPeriod: 3
    PivotPoints:
      Method: "standard"  # Options: standard, fibonacci, woodie, camarilla
  FeatureEngineering:
    IncludeExternalFactors: true
    WindowSizes: [1, 3, 5]  # For lagged features
    PriceFeatures:
      - close
      - high
      - low
      - open
  MachineLearning:
    Models:
      - RandomForest
      - GradientBoosting
      - LSTM
    Hyperparameters:
      RandomForest:
        n_estimators: 100
        max_depth: 10
      GradientBoosting:
        n_estimators: 100
        learning_rate: 0.1
      LSTM:
        units: 50
        dropout: 0.2
        epochs: 50
        batch_size: 32
    Targets:
      PricePrediction:
        Horizons: [1, 3, 5]  # Predict 1, 3, and 5 periods ahead
      DirectionPrediction:
        Threshold: 0.001  # 0.1% price movement threshold for direction